# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emma Caison
email: emmacai@live.unc.edu
description: INLS 161 Assignment 2
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emmacai.github.io" # the base hostname & protocol for your site
twitter_username: No Thanks
github_username:  emmacai

# Build settings
markdown: kramdown
